import customtkinter as ctk

BRAND_BLACK = "#000000"
BRAND_DARK = "#15181e"
BRAND_DEEP = "#0d0e12"

SURFACE_LIGHT = "#f1f2f3"
SURFACE_DARK = "#15181e"

BG_LIGHT = "#f1f2f3"
BG_DARK = "#0d0e12"

CARD_LIGHT = "#ffffff"
CARD_DARK = "#1a1d24"

BORDER_LIGHT = "#d5d7db"
BORDER_DARK = "#2e3038"

BORDER_SUBTLE_LIGHT = "#e8e9eb"
BORDER_SUBTLE_DARK = "#25272e"

HOVER_LIGHT = "#e8e9eb"
HOVER_DARK = "#25272e"

SIDEBAR_BG = "#0d0e12"
SIDEBAR_HOVER = "#1a1d24"
SIDEBAR_ACTIVE = "#1868f2"
SIDEBAR_TEXT = "#efeff1"
SIDEBAR_TEXT_HINT = "#656a76"
SIDEBAR_DIVIDER = "#25272e"

TEXT_ON_LIGHT = "#15181e"
TEXT_ON_DARK = "#efeff1"
TEXT_SECONDARY_LIGHT = "#3b3d45"
TEXT_SECONDARY_DARK = "#b2b6bd"
TEXT_HINT_LIGHT = "#656a76"
TEXT_HINT_DARK = "#656a76"

ACTION_BLUE = "#1868f2"
ACTION_BLUE_HOVER = "#2b89ff"
ACTION_BLUE_DARK = "#1060ff"

SUCCESS = "#10b981"
WARNING = "#bb5a00"
WARNING_BG = "#fbeabf"
ERROR = "#731e25"
ERROR_LIGHT = "#f5c1c5"

ACCENT_PURPLE = "#7b42bc"
ACCENT_TEAL = "#14c6cb"
ACCENT_ORANGE = "#a9722e"

SURFACE = (BG_LIGHT, BG_DARK)
CARD_BG = (CARD_LIGHT, CARD_DARK)
BORDER = (BORDER_LIGHT, BORDER_DARK)
BORDER_SUBTLE = (BORDER_SUBTLE_LIGHT, BORDER_SUBTLE_DARK)
HOVER_BG = (HOVER_LIGHT, HOVER_DARK)
TEXT_PRIMARY = (TEXT_ON_LIGHT, TEXT_ON_DARK)
TEXT_SECONDARY = (TEXT_SECONDARY_LIGHT, TEXT_SECONDARY_DARK)
TEXT_HINT = (TEXT_HINT_LIGHT, TEXT_HINT_DARK)
PAGE_BG = (BG_LIGHT, BG_DARK)

SECTION_COLORS = {
    "github": ACCENT_TEAL,
    "evaluation": ACCENT_PURPLE,
    "llm": ACTION_BLUE,
    "output": ACCENT_ORANGE,
    "app": BRAND_DARK,
}

SECTION_ICONS = {
    "github": "\u25C8",
    "evaluation": "\u25C6",
    "llm": "\u2B21",
    "output": "\u25CE",
    "app": "\u2699",
}

GITHUB_LANGUAGES = [
    "Python", "JavaScript", "TypeScript", "Java", "Go", "Rust",
    "C++", "C#", "C", "Ruby", "PHP", "Swift", "Kotlin", "Dart",
    "Shell", "HTML", "CSS", "Scala", "R", "Lua", "Perl",
    "Haskell", "Elixir", "Clojure", "Vue", "Svelte",
]

FONT_DISPLAY = (22, "bold")
FONT_PAGE_TITLE = (20, "bold")
FONT_DIALOG_TITLE = (16, "bold")
FONT_SECTION = (14, "bold")
FONT_LIST_TITLE = (13, "bold")
FONT_NAV = (13, "normal")
FONT_BODY = (12, "normal")
FONT_BODY_EMPH = (12, "bold")
FONT_BTN = (12, "normal")
FONT_BTN_BOLD = (12, "bold")
FONT_CAPTION = (11, "normal")
FONT_STATUS = (11, "normal")
FONT_STAT_VALUE = (28, "bold")
FONT_STAT_TITLE = (11, "normal")
FONT_ICON_SM = (14, "normal")
FONT_ICON_MD = (16, "bold")
FONT_LABEL = (11, "bold")

_font_cache = {}


def make_font(spec: tuple) -> ctk.CTkFont:
    if spec not in _font_cache:
        _font_cache[spec] = ctk.CTkFont(size=spec[0], weight=spec[1])
    return _font_cache[spec]


CORNER_RADIUS_NONE = 0
CORNER_RADIUS_MINIMAL = 2
CORNER_RADIUS_SUBTLE = 3
CORNER_RADIUS_STANDARD = 4
CORNER_RADIUS_COMFORTABLE = 5
CORNER_RADIUS_CARD = 6
CORNER_RADIUS_BTN = 4
CORNER_RADIUS_ENTRY = 4

PADDING_PAGE = 24
PADDING_CARD = 16
PADDING_SECTION = 12
PADDING_FIELD = 6

SIDEBAR_WIDTH = 200
TOPBAR_HEIGHT = 52
STATUSBAR_HEIGHT = 28
BTN_HEIGHT = 32
BTN_HEIGHT_SM = 28
ENTRY_HEIGHT = 32
FORM_LABEL_WIDTH = 120
SHORT_FIELD_WIDTH = 90
MEDIUM_FIELD_WIDTH = 180
LONG_FIELD_WIDTH = 320

BTN_PRIMARY_FG = (ACTION_BLUE, ACTION_BLUE_DARK)
BTN_PRIMARY_HOVER = (ACTION_BLUE_HOVER, ACTION_BLUE)
BTN_PRIMARY_TEXT = ("#ffffff", "#ffffff")

BTN_SECONDARY_FG = "transparent"
BTN_SECONDARY_HOVER = (HOVER_LIGHT, HOVER_DARK)
BTN_SECONDARY_BORDER = (BORDER_LIGHT, BORDER_DARK)
BTN_SECONDARY_TEXT = (TEXT_ON_LIGHT, TEXT_ON_DARK)

BTN_DANGER_FG = (ERROR, ERROR)
BTN_DANGER_HOVER = ("#5a161c", "#5a161c")
BTN_DANGER_TEXT = ("#ffffff", "#ffffff")

BTN_GHOST_FG = "transparent"
BTN_GHOST_HOVER = (HOVER_LIGHT, HOVER_DARK)
BTN_GHOST_TEXT = (TEXT_ON_LIGHT, TEXT_ON_DARK)
